spring.application.name=DAWI_T1_YUPANQUI_YAN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8099

spring.datasource.url=jdbc:mysql://localhost:3306/dawi_t1_yupanqui_yan
spring.datasource.username=root
spring.datasource.password=1234
